---
name: Pull Request Tests
on:
  pull_request:
    branches:
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable,nightly
          components: rustfmt
      - run: |
          cargo +nightly fmt --check
          cd acquire-runner
          cargo +nightly fmt --check -- --config-path ../.rustfmt.toml
  clippy:
    needs: format
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - run: |
          cargo clippy
          cd acquire-runner
          cargo clippy
  test:
    needs: clippy
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: |
          cd acquire-runner
          cargo test
